<?php

  /*
   * Do not edit this file!
   *
   * If any of these settings are invalid, you can override them in
   * local_settings.php
   */

$DB_HOST = 'mysql.internal';

$CENTRAL_HOST = $DB_HOST;
$CENTRAL_DB = 'mcx';
$CENTRAL_USER = 'medcommons';
$CENTRAL_PASS = '';

$IDENTITY_HOST = $CENTRAL_HOST;
$IDENTITY_DB = $CENTRAL_DB;
$IDENTITY_USER = $CENTRAL_USER;
$IDENTITY_PASS = $CENTRAL_PASS;

$DB_SETTINGS = array(
		     // PDO::ATTR_PERSISTENT => true,
		     PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
		     );

/*
 * source of mcrypt_create_iv random values.
 * http://us3.php.net/manual/en/function.mcrypt-create-iv.php
 *
 * possible values are:
 * MCRYPT_RAND            - required for Windows
 * MCRYPT_DEV_RANDOM      - totally secure
 * MCRYPT_DEV_URANDOM     - best value for Linux
 */
$MCRYPT_RAND_SOURCE = MCRYPT_DEV_URANDOM;

/*
 * Site-specific secret value...
 * override in local_settings.php and DONT SHARE WITH ANY OTHER SITE
 */
$SECRET = 'secret';

/**
 * Location of mcid service
 *
 * Choice is 
 *
 *  - to use python directly
 *  - to call the java identity server (which may or may not call python itself)
 *
 * Default configuration calls python service
 */
$URL = 'http://mcid.internal:1080/mcid';
$TRACKING_URL = 'http://mcid.internal:1080/tracking_number'; // Note: duplicated in secure/ws/wslibdb.inc.php
$NS = 'http://www.medcommons.net/mcid';

/*
 * Location of Identity Server Soap Service
 */
$IDENTITY_WS_URL = 'http://localhost:8080/identity/ws/AccountCreationServiceImpl';
$IDENTITY_WS_NS = '"http://ws.identity.medcommons.net"';

// Example settings for java identity server config
//
// $URL = 'https://www.medcommons.net/identity/ws/AccountCreationServiceImpl';
// $NS = '"http://ws.identity.medcommons.net"';

  $acDomain = 'www.medcommons.net';
  $acPrivacyPolicyFile = 'privacypolicy.html';
  $acCommonName = 'MedCommons';
  $acApplianceName = 'MedCommons Retail Appliance';
  $acPatientBrochureFile = 'patientbrochurefile.html';
  $acTemplateFolder = '/var/www/mc_templates/';
  $acPrintableTemplateFolder = 'PrintableTemplates/';
  $acEmailTemplateFolder = 'EmailTemplates/';
  $acAccountStatus = 'Requested,Scheduled,Created,Referred,Opened,Reported,Reviewed,Completed,Patient Opened,Copied to PHR,Deleted';
  $acPrivacyConfigurationFile = 'privacyconfig.html';
  $acOwner = 'MedCommons, Inc. 52 Marshall St, Watertown, MA';
  $acLogo = '/images/mc_logo.png';
  $acAlt = 'MedCommons Personalized Healthcare Appliance';
  $acHomePage = 'https://www.medcommons.net/';
  $acMessage = 'www.medcommons.net Personalized Healthcare 2.0';
  $acHomePageTemplate = 'baselinehp.inc.php';
  $acStyleSheet = '/style.css';
  $acFromName = 'MedCommons on Demand';
  $acFromEmail = 'noreply@medcommons.net';
  $acOnlineRegistration = '1';
  $acApplianceMode = '0'; // development
  $acGlobalsRoot = 'http://globals.myhealthespace.com/';
  $acOpenIDMode = 1;

  // The billing service supports queries for the billing counters
  $acBillingService = 'http://localhost/modpay/';

  // Set to true if billing features should be enabled.
  $acEnableBilling = false;

  $acResidentEditors = '0';

  $acGatewayRoot = "/opt/gateway";

  $acCookieDomain = False;
  $acScriptDomain = False;

  $acAmazonFPSKey = "075Q8TW5Y9HFW4ZZAG02";
  $acAmazonFPSSecret = "IMBRcy/Lb/uqrOLF7GTWI7emGKt120o+BDWgzcIa";
  $acAmazonPayUrl = 'https://authorize.payments.amazon.com/pba/paypipeline';

  $acAmazonProducts = array( 
        "DICOM10" =>  array( "price" => "USD  10.00", "counters" => array(0,2,0), "description" => "2 DICOM Uploads" ),
        "FAX20" =>  array( "price" => "USD 10.00", "counters" => array(20,0,0), "description" => "20 Inbound Fax Pages" ),
        "UNPRICED10" =>  array( "price" => "USD 10.00", "counters" => array(0,0,10), "description" => "10 ProBono Vouchers" )
      );


  // Global amazon redirector, ensures amazon return comes back to this appliance
  $acAmazonRedirectorUrl = 'https://www.medcommons.net/devpay/devpay_redir.php';

////////////////////////////////////////////
// Leave this at the very end of the file...
//

include 'local_settings.php';

$CENTRAL_PDO  = 'mysql:host=' . $CENTRAL_HOST  . ';dbname=' . $CENTRAL_DB;
$IDENTITY_PDO = 'mysql:host=' . $IDENTITY_HOST . ';dbname=' . $IDENTITY_DB;

if(!isset($MOD_HOST)) {
  // If no overriding settings are defined then assume that the database is 
  // the accounts database
  $MOD_HOST=$IDENTITY_HOST; 
  $MOD_USER=$IDENTITY_USER; 
  $MOD_DB=$IDENTITY_DB; 
  $MOD_PASS=$IDENTITY_PASS;
}

//
////////////////////////////////////////////

?>
