<?php

require_once "is.inc.php";
function dbgen($x,$formlib,$tablename)
{
	$out = '';
	$count = count ($x);
	for ($i=0; $i<$count; $i++)
	{
		$region = $x[$i][0];
		$rest = $x[$i][1];
		$count2 = count($rest);
		for ($j=0; $j<$count2; $j++ )
		{
			$zone =  $rest[$j][0];
			$remains = $rest[$j][1];
			$count3 = count ($remains);
			
				 	$name = makevarname($region.'-'.$zone.'-notes');
					$out.="-- text f_notes $name 
				$name varchar(255) not null,
				 "; 
				 
			for ($k=0;$k<$count3; $k++)
			{
				$cond = $remains[$k][0];
				$code = $remains [$k][1];

				if ($cond===false)
				{
					$name = makevarname($region.'-'.$zone);
					$out.="-- text f_$code $name
				$name varchar(255) not null,
				 "; 					
				}else
				{
					$name = makevarname($region.'-'.$zone.'-'.$cond);
					$out.="-- bool f_$code $name
				$name tinyint(1) not null,
				 "; 					
				}
			}
		}
	}
	$time = strftime('%D %T');
	$out ="
-- Generated by informedSports iform.php utility program
-- This  auto-generated file is used to create a custom form database table for Informed Sports 

-- Table structure for table $tablename
-- Created from schemata '$formlib' at $time;

CREATE TABLE IF NOT EXISTS $tablename (
 ind int(11) NOT NULL auto_increment,
  parentind int(11) not null,
  playerind int(11) not null,
  useropenid varchar (255) not null,
  
  $out
  time int(11) NOT NULL,
  PRIMARY KEY  (ind),
  KEY playerind (playerind)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=44 ;
	";
	return $out;
}


function mprint($x,$formlib,$table)
{
	
	$out  = "<h4>Every $table Table FIeld Mapped by schemata '$formlib' to Informed Sports Codes</h4>";
	$out .="These codes were developed by informed sports for internal use only
	";
	$out .= '<table>';
	$count = count ($x);
	for ($i=0; $i<$count; $i++)
	{
		$region = $x[$i][0];
		$rest = $x[$i][1];
		$count2 = count($rest);
		//if ($count2==0) echo "<br/>1: $region"; else
		for ($j=0; $j<$count2; $j++ )
		{
			$zone =  $rest[$j][0];
			$remains = $rest[$j][1];
			$count3 = count ($remains);

				$out.= "<tr><td>$region.$zone.notes</td><td>110101010</td>";
				 $out.= "<td>autogened</td></tr>";
			//if ($count3==0) echo"<br/>2: $region zone: $zone"; else
			for ($k=0;$k<$count3; $k++)
			{
				$cond = $remains[$k][0];
				$code = $remains [$k][1].'value';
				$out.= "<tr><td>$region.$zone.$cond</td><td>$code</td>";
				if ($cond===false) $out.="<td><b> text field </b></td></tr> "; else $out.= "<td>bool</td></tr>";
			}
		}
	}
	$out .='</table>';
	return $out;
}




$my_role=check_login('team,league,is','iform page'); // only returns if logged in
$flavor =(isset($_REQUEST['report']) )? $_REQUEST['report']:0;

// starts here

if (!isset($_REQUEST['formlib']) || (!isset($_REQUEST['table']))) die ('usage url?formlib=<spec>&table=<tab>&report=nnn [&db | &form ]');
$formlib = $_REQUEST['formlib']; // life if.inc.php





require_once $formlib;

$ggg = schema(); // must be inside $formlib
$table = dbtab(); // get table name from include file

if (isset($_REQUEST['db']))
{
	header("Content-type: text/plain");
	echo dbgen($ggg,$formlib,$table);
	exit;

} else

{

	echo mprint($ggg,$formlib,$table);
}
echo "</body></html>";
?>