<?

$emailAddress = $_REQUEST['emailAddress'];

	if (!$_REQUEST['emailAddress']) {
		print "Your email address was not found in the input.<br/>\n";
		print "--&gt; <a href=\"index.php?area=apply\">Try again</a><br/>\n";
	}

	else {


		if (!$_REQUEST['sent']) {
			//print "<b>Sending the secret to your email address...</b><br/>";
			flush();

			if (get_magic_quotes_gpc()) {
				$emailAddress = stripslashes($_REQUEST['emailAddress']);
			}
			else {
				$emailAddress = &$_REQUEST['emailAddress'];
			}

			$secretMessage = md5($config['passPhrase'] . $emailAddress);
			$urlEmail = urlencode($emailAddress);
			$requestURI = preg_replace('/\?.*/', '', $_SERVER['REQUEST_URI']);
$headers = 'From: certadmin@medcommons.net' . "\r\n" .
   'Reply-To: postmaster@medcommons.net' . "\r\n" .
   'X-Mailer: PHP/' . phpversion();
			$message = <<<ENDE
Greetings from  the {$config["orgName"]} Certificate Authority. You have been invited to join our secure operations network running at https://ops.medcommons.net

If you do not complete this process, you will be unable to access https://ops.medcommons.net

Here is your personal secret:
	$secretMessage

click this URL to enter your secret:
https://{$_SERVER['HTTP_HOST']}{$requestURI}?area=apply&stage=enterKey&sent=1&emailAddress=$urlEmail&t=$t&o=$o&msg=$secretMessage

Regards,

{$config["orgName"]} Certificate Authority.
mailto:{$config["contact"]}
ENDE;

			mail($emailAddress, "Your secret from the {$config["orgName"]} CA", $message, $headers);

			//print "Done<br/><br/>\n";
		}
?>

<table border="0"> <tbody><tr><td><img src="images/MEDcommons_logo_246x50_002.gif" alt="medcommons, inc." height="50" width="246"></td>
<td><h4>Enter Secret Code for <?=$t?></h4></td><td><small><a href="/ca/php-ca/start.htm">ca home</a></small></td></tr></tbody></table><br>
<p>

</p><p>
You are here because you have clicked on an email generated by the MedCommons Certificate Authority.
</p>

<p>
Please enter the secret code from that email in order to generate a certificate for <?=$t?>
</p>


<form method="post" action="index.php">
<input type="hidden" name="area" value="apply">
<input type="hidden" name="stage" value="issueCert">
<input type="hidden" name="o" value="<?=$o?>">
<input type="hidden" name="t" value="<?=$t?>">
<input type="hidden" name="emailAddress" value="<?=htmlspecialchars($emailAddress)?>">
        <fieldset style="width: 400px;">
                <legend>Email address validation</legend>
                <p>
                Please enter the secret sent to you by MedCommons in the following box:
                </p>

                <table>
                <colgroup><col width="180px"></colgroup>
                <tr><th>Secret</th><td><input type="text" name="secret" value="<?=$secretmsg?>" size="40"></td></tr>

                <tr><td colspan=2 style="text-align: right;"><input type="submit" value="Check the secret"></td></tr>
                </table>
        </fieldset>
</form>

<p>
<table><tbody><tr>
<td><img src="images/MEDcommons_logo_246x50.gif"></td>
<td><img src="images/diag_astmlogo.gif"></td>
<td><img src="images/PingFederate%2520Logo.gif"></td>
<td><img src="images/verisignimage.jpg"></td>
<td><img src="images/identrus.jpg"></td>
</tr>
</tbody></table>
</p>
<?

	}

?>
