<?php
require 'urls.inc.php'; // needs symbols but no database
require 'cxppostget.inc.php';


// donner 09 sep 06
// accept incoming REST call, assemble ccrs and docs ,  return XML
//
// args:
//		 a=pipe delimited list of args
//		 c=command string
//		 mckey = medcommons widget key

function bx($mckey)
{
	$sig = "bills signature";
	// this function does the backup work
	// $a = url of acct rest server
	// $b = mckey
	$au = $GLOBALS['Accounts_Url']."A.php?format=pipe&mckey=$mckey";
	//echo $au;
	$hresult = file_get_contents($au);
	//echo "result $result";
	//
	$docs='';
	$doclist = explode ('|',file_get_contents($GLOBALS['Commons_Url']."G.php?format=pipe&guids=$hresult"));
	$count =0;
	foreach ($doclist as $doc) {
		list($guidd,$gurl) = explode(',',$doc);
		$result = cxppostget($gurl.'/CxpRestServlet',$guidd);
		if ($result === false) $result = "<error>cxp failed to access $gurl with $guidd</error>";
		$docs .= "<doc><guid>".$guidd."</guid>\r\n<ccrcontents>\r\n$result\r\n</ccrcontents></doc>";
		if ($count++ > 8) break; // just do one
	};


	return array ($sig,"<saveset><header>$hresult</header><body>$docs</body></saveset>");
}

if (!isset($_REQUEST['c'])) $c='do'; else
$c= $_REQUEST['c'];


//require mckey for now
if (!isset($_REQUEST['mckey'])) die("Must supply &mckey to work remotely");
$sha1=false;$accid=false;$email=false; //prepare for the worst
if (isset($_REQUEST['mckey']))
{
	// if supplied, use it
	$mckey= $_REQUEST['mckey'];
	$mckeyparts = explode('|',base64_decode($mckey));
	if (isset($mckeyparts[0])) $sha1 = $mckeyparts[0];
	if (isset($mckeyparts[1])) $accid = $mckeyparts[1];
	if (isset($mckeyparts[2])) $email = $mckeyparts[2];
	if ($sha1===false || $accid===false || $email===false) die ('This mckey appears invalid, try again');
}


// use the command code to figure out what the caller wants to get back

switch ($c){

	case'form'	:{
		if (isset($mckey)) $mckey = "<tr><td>mckey</td><td><i>hidden</i><input type='hidden' name='mckey' value='$mckey' /></td></tr>\r\n";
		else $mckey='';
		$gmt = gmstrftime("%b %d %Y %H:%M:%S");
		$uri = htmlspecialchars($_SERVER["REQUEST_METHOD"].' '.$_SERVER ['REQUEST_URI']);
		$aout ="processed by ".$_SERVER['HTTP_HOST'].' '.$_SERVER['SERVER_ADDR'].':'.
		$_SERVER['SERVER_PORT']." $gmt GMT";

		$out = <<<XXX
<!-- form generated by Bx server $uri $aout -->
<h4>test form generated by Bxserver $aout</h4>
<i>View source, copy and paste to your editor, customize this as you see fit, and pasteinto your own application, wiki, blog, or web site</i>
<form method='POST' action='Bx.php'>
<table>
$mckey
<tr><td>accserver</td><td><i>hidden</i><input type='hidden' name='arga' value='Bx.php' /></td></tr>\r\n
<tr><td>command</td><td><i>hidden hardwired to 'xml'</i><input type='hidden' name='c' value='xml' /></td></tr>\r\n
<tr><td>argj</td><td><input type=text name='argj' value='ARGJ' /></td></tr>\r\n
<tr><td>submit</td><td><input type=submit name='submit' value='try it' /></td></tr>\r\n
</table>
</form>
<!-- end of form generated from Bx server  -->
XXX;
		header ("Content-type: text/html");
		break;
	}
	case 'xml':
	case 'do': {
		list ($sig,$xml) = bx($mckey);
		$gmt = gmstrftime("%b %d %Y %H:%M:%S");
		$uri = htmlspecialchars($_SERVER["REQUEST_METHOD"].' '.$_SERVER ['REQUEST_URI']);
		$aout ="<details>processed by ".$_SERVER['HTTP_HOST'].' '.$_SERVER['SERVER_ADDR'].':'.
		$_SERVER['SERVER_PORT']." $gmt GMT</details>";
		$aout.= "<requesturi>\n".$uri."</requesturi>\n";
		$out = <<<XXX
<bxreturn>
    $aout
	<sig>$sig</sig>
	<bx>$xml</bx>
	<bxstatus>success</bxstatus>
</bxreturn>
XXX;
		if ($c=='do') header ("Content-type: text/xml"); else
		header ("Content-type: application/x-text");
		break;
	}




	default: break;
}

echo $out;
?>