<?php
require_once "is.inc.php";

function linewrap ($s)
{
	return "
	$s";
}

//main starts here
header("Content-type: application/octet-stream");
header("Content-Disposition: attachment; filename=\"stdump.inc.php\"");

$viewers = array('viewA','viewB','viewC','viewD','viewE');

$ops = array ('code_gen');//,'create_schema');


$gmt = strftime('%T %D');
echo "<?php
//generated by stcodebuilder.php
//

";
$tables=array();//a full platter of tables
$code ="
function make_body ()
{ \$m=\$js=\$nav='';
";

$result = dosql("Select distinct ddtable from dumporder order by displayorder");
while ($r=isdb_fetch_object($result)) 
{
$tables[] = $r->ddtable;
$code .= "list (\$m,\$js,\$nav)=onetab('viewA','$r->orientation','$r->ddtable','$r->label','$r->$ddtable-markup','$r->sortkey','$r->extra' );
\$alltabs.=\$m; \$alljs.=\$js; \$navsetmid .=\$nav;
";
}
$code.='
return \$nav.\$alltabs.\$alljs;
}
';

linewrap ('/* function to enumerate tables *',$code,'');

mysql_free_result($result);
//do the same thing for each distinct table

	foreach ($ops as $op)
	{
		foreach ($tables as $table)
		{
		$mid='';
		switch ($op)
		{

			case 'code_gen':
				$top = <<<XXX
				
/* fields for table $table generated by MedCommons stdumpbuilder @ $gmt */
		
XXX;

$result = dosql("Select * from datadictionary where ddtable='$table' ");
while ($r=isdb_fetch_array($result)) {$fn=$r['fieldname']; 
//print_r ($r);
$fn= $r['fieldname'];

$mid.=' 
$labels_'."['$table']"."['".$fn."'] = ".'"'.$r['reportwriterheading'].'";  '; 

$mid.='
$names_'."['$table']"."['".$fn."'] = ".'"'.$r['fieldname'].'";  '; 


foreach ($viewers as $viewer) if ($r[$viewer]) $mid.='
$viewer_'."['$viewer']"."['$table']"."['".$fn."'] = ".'"'.$r['fieldname'].'";  ';  
}
				mysql_free_result($result);
				$bottom ="

";				
				break;
			default: die ("Invalid op $op");
		}
		echo linewrap($top).$mid.linewrap($bottom);
	}

	echo "//end of generated code
	?>";
}
//that's about all
?>