<?php
require_once "is.inc.php";
function linewrap ($s)
{
	return "
	$s";
}
function code()
{
	$code ="
function make_section_tabs ()
{ \$alltabs=\$alljs=\$navsetmid='';
";
$first=true;
$result = dosql("Select * from viewerorder order by displayorder");
while ($r=isdb_fetch_object($result))
{
	if (!isset($tablesloaded [$r->ddtable])) {
	$code .= "\$_$r->ddtable = load_table('$r->ddtable');
	";	
	$tablesloaded [$r->ddtable]=true;
	}
	
	$extra = ($first?"'class=selected'":"''");
	//	onesection('$r->label','$r->label-section-markup','$r->tab' );
	if ($r->displaystyle=='vertical')
	$code .= "list (\$m,\$js,\$nav)=onetab_vertical (\$_$r->ddtable,'viewA', '$r->tab','$r->ddtable','$r->label','$r->ddtable-$r->label-markup','$r->sortkey',
	$extra);

	\$alltabs.=\$m; \$alljs.=\$js; \$navsetmid .=\$nav;
";
	else
	$code .= "list (\$m,\$js,\$nav)=onetab_horizontal(\$_$r->ddtable,'viewA','$r->tab','$r->ddtable','$r->label','$r->ddtable-$r->label-markup','$r->sortkey',$extra );
	\$alltabs.=\$m; \$alljs.=\$js; \$navsetmid .=\$nav;
";
	$first = false;
}

mysql_free_result($result);

$code.='$nav = '."'".'<div id="demo" class="yui-navset">
<ul class="yui-nav">'."'".
		".\$navsetmid."."'".'</ul>  
<div class="yui-content"> '."';"."			
return \$nav.\$alltabs.\$alljs;
}
";

return linewrap ('/* function to enumerate tabs */').linewrap ($code);

}
//main starts here
header("Content-type: application/octet-stream");
header("Content-Disposition: attachment; filename=\"stview.inc.php\"");
$viewers=array('viewA','viewB');

$gmt = strftime('%T %D');
echo "<?php
//generated by MedCommons stviewbuilder @ $gmt
//

";
$tables=array();//a full platter of tables



$result = dosql("Select distinct source from tabparts");
while ($r=mysql_fetch_object($result)) {
	echo linewrap('$tables_[] = "'.$r->source.'";');
}
mysql_free_result($result);
$result = dosql("Select * from viewerorder");
while ($r1=mysql_fetch_object($result)) {
	$tabkey= $r1->tab;
	$displaystyle = $r1->displaystyle;
	if ($displaystyle=='horizontal') $tabkey = $r1->ddtable; // if this is a horizontal display, go do table
	$mid='';
	$top = <<<XXX
	/* fields for tab $tabkey  $displaystyle */
			
XXX;
	$once = true;
		if ($displaystyle=='horizontal')
	$result2 = dosql("Select * from datadictionary where ddtable='$tabkey' "); else

	$result2 = dosql("Select * from datadictionary where substr(tab,1,1)= '$tabkey' ");
	while ($r=mysql_fetch_array($result2)) {
		$fn=$r['fieldname'];
		$mid.='
$labels_'."['$tabkey']"."['".$fn."'] = ".'"'.$r['reportwriterheading'].'";  '; 


		$mid.='$fields_'."['$tabkey']"."['".$fn."'] = ".'"'.$r['fieldname'].'";  '; 	
		foreach ($viewers as $viewer) 
		if ($r[$viewer]) $mid.='$viewer_'."['$viewer']"."['$tabkey']"."['".$fn."'] = ".'"'.$r['fieldname'].'";  ';  


		if ($once) {$mid.='$src_'."['$tabkey']"."= ".'"'.$r['ddtable'].'";  ';
			$once = false;
		}

	}
	$bottom ="

";				
	
	echo linewrap($top).$mid.linewrap($bottom);

	mysql_free_result($result2);
}

echo code()."
//end of generated code
?>";
//that's about all
?>