<?php


function standard_searchbox()
{
	$out = <<<XXX
	<p><small><form action='topics.php' method='POST'>
	Search by topic or keyword: <input type=hidden value='search' name='search'>
	<input type=text value='' name=filter >
	<input type=submit value='Search' name=submit> you can also specify part of a group name
	</form></small></p>
XXX;
	$alpha = <<<XXX
                <span style="font-size: .7em" ><a href="?a=a">A</a>                                &nbsp;<a href="?a=b">B</a>                                &nbsp;<a href="?a=c">C</a>                                &nbsp;<a href="?a=d">D</a>
                                &nbsp;<a href="?a=e">E</a>                                &nbsp;<a href="?a=f">F</a>                                &nbsp;<a href="?a=g">G</a>                                &nbsp;<a href="?a=h">H</a>
                                &nbsp;<a href="?a=i">I</a>                                &nbsp;<a href="?a=j">J</a>                                &nbsp;<a href="?a=k">K</a>                                &nbsp;<a href="?a=l">L</a>
                                &nbsp;<a href="?a=m">M</a>                                &nbsp;<a href="?a=n">N</a>                                &nbsp;<a href="?a=o">O</a>                                &nbsp;<a href="?a=p">P</a>
                                &nbsp;<a href="?a=q">Q</a>                                &nbsp;<a href="?a=r">R</a>                                &nbsp;<a href="?a=s">S</a>                                &nbsp;<a href="?a=t">T</a>
                                &nbsp;<a href="?a=u">U</a>                                &nbsp;<a href="?a=v">V</a>                                &nbsp;<a href="?a=w">W</a>                &nbsp;<a href="?a=x">X</a>
                &nbsp;<a href="?a=y">Y</a>                &nbsp;<a href="?a=z">Z</a>          &nbsp;<a href="?all">List of All Topics</a></span>
XXX;

	$x  = <<<XXX
	<p><small><form action='topics.php' method='POST'>
Select a direct topic: <select name="ord">
<option value='1'>Abdominal Pain</option>
 <option value='2'>Abortion</option>
 <option value='3'>Abscesses</option>
 <option value='4'>Acne</option>
 <option value='5'>Acoustic Neuroma</option>
 <option value='6'>Acupuncture</option>
 <option value='7'>Addison's Disease</option>
 <option value='8'>Adhesions</option>
 <option value='9'>Adoption</option>
 <option value='10'>Adrenal Gland Disorders</option>
 <option value='11'>Advance Directives</option>
 <option value='12'>African-American Health</option>
 <option value='13'>AIDS</option>
 <option value='14'>AIDS and Infections</option>
 <option value='15'>AIDS and Pregnancy</option>
 <option value='16'>AIDS Medicines</option>
 <option value='17'>AIDS--Living with AIDS</option>
 <option value='18'>Air Pollution</option>
 <option value='19'>Alcohol and Youth</option>
 <option value='20'>Alcohol Consumption</option>
 <option value='21'>Alcoholism</option>
 <option value='22'>Allergy</option>
 <option value='23'>Alpha-1 Antitrypsin Deficiency</option>
 <option value='24'>Alzheimer's Caregivers</option>
 <option value='25'>Alzheimer's Disease</option>
 <option value='26'>Amputees</option>
 <option value='27'>Amyotrophic Lateral Sclerosis</option>
 <option value='28'>Anabolic Steroids</option>
 <option value='29'>Anal and Rectal Diseases</option>
 <option value='30'>Anal Cancer</option>
 <option value='31'>Anatomy</option>
 <option value='32'>Anemia</option>
 <option value='33'>Anesthesia</option>
 <option value='34'>Aneurysms</option>
 <option value='35'>Angina</option>
 <option value='36'>Angioplasty</option>
 <option value='37'>Animal Bites</option>
 <option value='38'>Animal Diseases and Your Health</option>
 <option value='39'>Ankle Injuries and Disorders</option>
 <option value='40'>Ankylosing Spondylitis</option>
 <option value='41'>Anthrax</option>
 <option value='42'>Antibiotics</option>
 <option value='43'>Antidepressants</option>
 <option value='44'>Antioxidants</option>
 <option value='45'>Anxiety</option>
 <option value='46'>Aphasia</option>
 <option value='47'>Appendicitis</option>
 <option value='48'>Arm Injuries and Disorders</option>
 <option value='49'>Arrhythmia</option>
 <option value='50'>Arsenic</option>
 <option value='51'>Arteriovenous Malformations</option>
 <option value='52'>Arthritis</option>
 <option value='53'>Asbestos</option>
 <option value='54'>Asian-American Health</option>
 <option value='55'>Asperger's Syndrome</option>
 <option value='56'>Assisted Living</option>
 <option value='57'>Assistive Devices</option>
 <option value='58'>Asthma</option>
 <option value='59'>Asthma in Children</option>
 <option value='60'>Ataxia Telangiectasia</option>
 <option value='61'>Athlete's Foot</option>
 <option value='62'>Attention Deficit Hyperactivity Disorder</option>
 <option value='63'>Autism</option>
 <option value='64'>Autoimmune Diseases</option>
 <option value='65'>Autonomic Nervous System Disorders</option>
 <option value='66'>Back Injuries</option>
 <option value='67'>Back Pain</option>
 <option value='68'>Bacterial Infections</option>
 <option value='69'>Behcet's Syndrome</option>
 <option value='70'>Bell's Palsy</option>
 <option value='71'>Benign Tumors</option>
 <option value='72'>Bereavement</option>
 <option value='73'>Bile Duct Diseases</option>
 <option value='74'>Biodefense and Bioterrorism</option>
 <option value='75'>Bipolar Disorder</option>
 <option value='76'>Bird Flu</option>
 <option value='77'>Birth Control</option>
 <option value='78'>Birth Defects</option>
 <option value='79'>Bladder Cancer</option>
 <option value='80'>Bladder Diseases</option>
 <option value='81'>Bleeding Disorders</option>
 <option value='82'>Blood and Blood Disorders</option>
 <option value='83'>Blood Transfusion and Donation</option>
 <option value='84'>Bone Cancer</option>
 <option value='85'>Bone Diseases</option>
 <option value='86'>Bone Grafts</option>
 <option value='87'>Bone Marrow Diseases</option>
 <option value='88'>Bone Marrow Transplantation</option>
 <option value='89'>Botox</option>
 <option value='90'>Botulism</option>
 <option value='91'>Brain Cancer</option>
 <option value='92'>Brain Diseases</option>
 <option value='93'>Breast Cancer</option>
 <option value='94'>Breast Diseases</option>
 <option value='95'>Breast Feeding</option>
 <option value='96'>Breast Reconstruction</option>
 <option value='97'>Breathing Problems</option>
 <option value='98'>Bronchitis</option>
 <option value='99'>Bruises</option>
 <option value='100'>Bullying</option>
 <option value='101'>Burns</option>
 <option value='102'>Bursitis</option>
 <option value='103'>Caffeine</option>
 <option value='104'>Calcium</option>
 <option value='105'>Cancer</option>
 <option value='106'>Cancer Alternative Therapies</option>
 <option value='107'>Cancer Chemotherapy</option>
 <option value='108'>Cancer in Children</option>
 <option value='109'>Cancer--Living with Cancer</option>
 <option value='110'>Carbohydrates</option>
 <option value='111'>Carbon Monoxide Poisoning</option>
 <option value='112'>Carcinoid Tumors</option>
 <option value='113'>Cardiac Arrest</option>
 <option value='114'>Cardiomyopathy</option>
 <option value='115'>Caregivers</option>
 <option value='116'>Carotid Artery Disease</option>
 <option value='117'>Carpal Tunnel Syndrome</option>
 <option value='118'>Cartilage Disorders</option>
 <option value='119'>Cat Scratch Disease</option>
 <option value='120'>Cataract</option>
 <option value='121'>Celiac Disease</option>
 <option value='122'>Cellulitis</option>
 <option value='123'>Cerebral Palsy</option>
 <option value='124'>Cervical Cancer</option>
 <option value='125'>Cesarean Section</option>
 <option value='126'>Chagas Disease</option>
 <option value='127'>Charcot-Marie-Tooth Disease</option>
 <option value='128'>Chemical Weapons</option>
 <option value='129'>Chickenpox</option>
 <option value='130'>Child Abuse</option>
 <option value='131'>Child Behavior Disorders</option>
 <option value='132'>Child Care</option>
 <option value='133'>Child Dental Health</option>
 <option value='134'>Child Development</option>
 <option value='135'>Child Mental Health</option>
 <option value='136'>Child Nutrition</option>
 <option value='137'>Child Safety</option>
 <option value='138'>Child Sexual Abuse</option>
 <option value='139'>Childbirth</option>
 <option value='140'>Childhood Brain Tumors</option>
 <option value='141'>Childhood Immunization</option>
 <option value='142'>Children's Health</option>
 <option value='143'>Children's Page</option>
 <option value='144'>Chiropractic</option>
 <option value='145'>Chlamydia Infections</option>
 <option value='146'>Choking</option>
 <option value='147'>Cholesterol</option>
 <option value='148'>Choosing a Doctor or Health Care Service</option>
 <option value='149'>Chronic Fatigue Syndrome</option>
 <option value='150'>Circumcision</option>
 <option value='151'>Cirrhosis</option>
 <option value='152'>Cleft Lip and Palate</option>
 <option value='153'>Clinical Trials</option>
 <option value='154'>Cloning</option>
 <option value='155'>Club Drugs</option>
 <option value='156'>Cocaine</option>
 <option value='157'>Colonic Diseases</option>
 <option value='158'>Colonic Polyps</option>
 <option value='159'>Color Blindness</option>
 <option value='160'>Colorectal Cancer</option>
 <option value='161'>Common Cold</option>
 <option value='162'>Complementary and Alternative Medicine</option>
 <option value='163'>Complex Regional Pain Syndrome</option>
 <option value='164'>Compulsive Gambling</option>
 <option value='165'>Congenital Heart Defects</option>
 <option value='166'>Connective Tissue Disorders</option>
 <option value='167'>Constipation</option>
 <option value='168'>COPD (Chronic Obstructive Pulmonary Disease)</option>
 <option value='169'>Coping with Chronic Illness</option>
 <option value='170'>Coping with Disasters</option>
 <option value='171'>Coronary Artery Bypass Surgery</option>
 <option value='172'>Coronary Artery Disease</option>
 <option value='173'>Cosmetic Dentistry</option>
 <option value='174'>Cosmetics</option>
 <option value='175'>Cough</option>
 <option value='176'>CPR</option>
 <option value='177'>Creutzfeldt-Jakob Disease</option>
 <option value='178'>Critical Care</option>
 <option value='179'>Crohn's Disease</option>
 <option value='180'>Cryptosporidiosis</option>
 <option value='181'>CT Scans</option>
 <option value='182'>Cushing's Syndrome</option>
 <option value='183'>Cystic Fibrosis</option>
 <option value='184'>Cytomegalovirus Infections</option>
 <option value='185'>Degenerative Nerve Diseases</option>
 <option value='186'>Dementia</option>
 <option value='187'>Dengue</option>
 <option value='188'>Dental Health</option>
 <option value='189'>Dentures</option>
 <option value='190'>Depression</option>
 <option value='191'>Developmental Disabilities</option>
 <option value='192'>Diabetes</option>
 <option value='193'>Diabetes and Pregnancy</option>
 <option value='194'>Diabetes Insipidus</option>
 <option value='195'>Diabetes Type 1</option>
 <option value='196'>Diabetic Diet</option>
 <option value='197'>Diabetic Eye Problems</option>
 <option value='198'>Diabetic Foot</option>
 <option value='199'>Diabetic Kidney Problems</option>
 <option value='200'>Diabetic Nerve Problems</option>
 <option value='201'>Diagnostic Imaging</option>
 <option value='202'>Dialysis</option>
 <option value='203'>Diarrhea</option>
 <option value='204'>Dietary Fats</option>
 <option value='205'>Dietary Fiber</option>
 <option value='206'>Dietary Proteins</option>
 <option value='207'>Dietary Sodium</option>
 <option value='208'>Dietary Supplements</option>
 <option value='209'>Digestive Diseases</option>
 <option value='210'>Diphtheria</option>
 <option value='211'>Disabilities</option>
 <option value='212'>Disaster Preparation and Recovery</option>
 <option value='213'>Dislocations</option>
 <option value='214'>Diverticulosis and Diverticulitis</option>
 <option value='215'>Divorce</option>
 <option value='216'>Dizziness and Vertigo</option>
 <option value='217'>Domestic Violence</option>
 <option value='218'>Down Syndrome</option>
 <option value='219'>Drinking Water</option>
 <option value='220'>Drowning</option>
 <option value='221'>Drug Abuse</option>
 <option value='222'>Drug Safety</option>
 <option value='223'>Dual Diagnosis</option>
 <option value='224'>Dwarfism</option>
 <option value='225'>Dystonia</option>
 <option value='226'>E. Coli Infections</option>
 <option value='227'>Ear Disorders</option>
 <option value='228'>Ear Infections</option>
 <option value='229'>Eating Disorders</option>
 <option value='230'>Eczema</option>
 <option value='231'>Edema</option>
 <option value='232'>Ehlers-Danlos Syndrome</option>
 <option value='233'>Elbow Injuries and Disorders</option>
 <option value='234'>Elder Abuse</option>
 <option value='235'>Electromagnetic Fields</option>
 <option value='236'>Emergency Medical Services</option>
 <option value='237'>Emphysema</option>
 <option value='238'>Encephalitis</option>
 <option value='239'>End of Life Issues</option>
 <option value='240'>Endocarditis</option>
 <option value='241'>Endocrine Diseases</option>
 <option value='242'>Endometriosis</option>
 <option value='243'>Endoscopy</option>
 <option value='244'>Environmental Health</option>
 <option value='245'>Epilepsy</option>
 <option value='246'>Erectile Dysfunction</option>
 <option value='247'>Ergonomics</option>
 <option value='248'>Esophageal Cancer</option>
 <option value='249'>Esophagus Disorders</option>
 <option value='250'>Evaluating Health Information</option>
 <option value='251'>Exercise and Physical Fitness</option>
 <option value='252'>Exercise for Children</option>
 <option value='253'>Exercise for Seniors</option>
 <option value='254'>Eye Cancer</option>
 <option value='255'>Eye Diseases</option>
 <option value='256'>Eye Infections</option>
 <option value='257'>Eye Injuries</option>
 <option value='258'>Eye Wear</option>
 <option value='259'>Facial Injuries and Disorders</option>
 <option value='260'>Fainting</option>
 <option value='261'>Falls</option>
 <option value='262'>Family History</option>
 <option value='263'>Family Issues</option>
 <option value='264'>Farm Health and Safety</option>
 <option value='265'>Female Sexual Dysfunction</option>
 <option value='266'>Fetal Alcohol Syndrome</option>
 <option value='267'>Fever</option>
 <option value='268'>Fibromyalgia</option>
 <option value='269'>Fifth Disease</option>
 <option value='270'>Financial Assistance</option>
 <option value='271'>Fire Safety</option>
 <option value='272'>First Aid</option>
 <option value='273'>Fistulas</option>
 <option value='274'>Flu</option>
 <option value='275'>Fluid and Electrolyte Balance</option>
 <option value='276'>Folic Acid</option>
 <option value='277'>Food Allergy</option>
 <option value='278'>Food Contamination and Poisoning</option>
 <option value='279'>Food Labeling</option>
 <option value='280'>Food Safety</option>
 <option value='281'>Foot Health</option>
 <option value='282'>Foot Injuries and Disorders</option>
 <option value='283'>Fractures</option>
 <option value='284'>Fragile X Syndrome</option>
 <option value='285'>Friedreich's Ataxia</option>
 <option value='286'>Fungal Infections</option>
 <option value='287'>Gallbladder Diseases</option>
 <option value='288'>Gas</option>
 <option value='289'>Gastroenteritis</option>
 <option value='290'>Gastrointestinal Bleeding</option>
 <option value='291'>Gaucher's Disease</option>
 <option value='292'>Gay and Lesbian Health</option>
 <option value='293'>Genes and Gene Therapy</option>
 <option value='294'>Genetic Brain Disorders</option>
 <option value='295'>Genetic Counseling</option>
 <option value='296'>Genetic Disorders</option>
 <option value='297'>Genetic Testing</option>
 <option value='298'>Genital Warts</option>
 <option value='299'>GERD</option>
 <option value='300'>Germs and Hygiene</option>
 <option value='301'>Giardia Infections</option>
 <option value='302'>Glaucoma</option>
 <option value='303'>Gonorrhea</option>
 <option value='304'>Gout</option>
 <option value='305'>Growth Disorders</option>
 <option value='306'>Guillain-Barre Syndrome</option>
 <option value='307'>Gum Disease</option>
 <option value='308'>Hair Diseases and Hair Loss</option>
 <option value='309'>Hand Injuries and Disorders</option>
 <option value='310'>Hantavirus Infections</option>
 <option value='311'>Hazardous Waste</option>
 <option value='312'>Head and Brain Injuries</option>
 <option value='313'>Head and Brain Malformations</option>
 <option value='314'>Head and Neck Cancer</option>
 <option value='315'>Head Lice</option>
 <option value='316'>Headache</option>
 <option value='317'>Health Facilities</option>
 <option value='318'>Health Fraud</option>
 <option value='319'>Health Insurance</option>
 <option value='320'>Health Occupations</option>
 <option value='321'>Health Screening</option>
 <option value='322'>Health Statistics</option>
 <option value='323'>Healthy Living</option>
 <option value='324'>Hearing Disorders and Deafness</option>
 <option value='325'>Hearing Problems in Children</option>
 <option value='326'>Heart Attack</option>
 <option value='327'>Heart Disease in Women</option>
 <option value='328'>Heart Diseases</option>
 <option value='329'>Heart Diseases--Prevention</option>
 <option value='330'>Heart Failure</option>
 <option value='331'>Heart Surgery</option>
 <option value='332'>Heart Transplantation</option>
 <option value='333'>Heart Valve Diseases</option>
 <option value='334'>Heartburn</option>
 <option value='335'>Heat Illness</option>
 <option value='336'>Heel Injuries and Disorders</option>
 <option value='337'>Hemochromatosis</option>
 <option value='338'>Hemophilia</option>
 <option value='339'>Hemorrhagic Fevers</option>
 <option value='340'>Hemorrhoids</option>
 <option value='341'>Hepatitis</option>
 <option value='342'>Hepatitis A</option>
 <option value='343'>Hepatitis B</option>
 <option value='344'>Hepatitis C</option>
 <option value='345'>Herbal Medicine</option>
 <option value='346'>Hernia</option>
 <option value='347'>Herniated Disk</option>
 <option value='348'>Heroin</option>
 <option value='349'>Herpes Simplex</option>
 <option value='350'>Hiatal Hernia</option>
 <option value='351'>Hidradenitis Suppurativa</option>
 <option value='352'>High Blood Pressure</option>
 <option value='353'>High Blood Pressure in Pregnancy</option>
 <option value='354'>High Risk Pregnancy</option>
 <option value='355'>Hip Injuries and Disorders</option>
 <option value='356'>Hip Replacement</option>
 <option value='357'>Hispanic-American Health</option>
 <option value='358'>Hives</option>
 <option value='359'>Hodgkin's Disease</option>
 <option value='360'>Home Care Services</option>
 <option value='361'>Homeless Health Concerns</option>
 <option value='362'>Hormone Replacement Therapy</option>
 <option value='363'>Hormones</option>
 <option value='364'>Hospice Care</option>
 <option value='365'>Household Products</option>
 <option value='366'>HPV</option>
 <option value='367'>Huntington's Disease</option>
 <option value='368'>Hydrocephalus</option>
 <option value='369'>Hypoglycemia</option>
 <option value='370'>Hypothermia</option>
 <option value='371'>Hysterectomy</option>
 <option value='372'>Immune System and Disorders</option>
 <option value='373'>Immunization</option>
 <option value='374'>Impetigo</option>
 <option value='375'>Indigestion</option>
 <option value='376'>Indoor Air Pollution</option>
 <option value='377'>Infant and Newborn Care</option>
 <option value='378'>Infant and Toddler Development</option>
 <option value='379'>Infant and Toddler Health</option>
 <option value='380'>Infant and Toddler Nutrition</option>
 <option value='381'>Infection Control</option>
 <option value='382'>Infections and Pregnancy</option>
 <option value='383'>Infectious Diseases</option>
 <option value='384'>Infectious Mononucleosis</option>
 <option value='385'>Infertility</option>
 <option value='386'>Inhalants</option>
 <option value='387'>Injuries</option>
 <option value='388'>Insect Bites and Stings</option>
 <option value='389'>International Health</option>
 <option value='390'>Interstitial Cystitis</option>
 <option value='391'>Intestinal Cancer</option>
 <option value='392'>Irritable Bowel Syndrome</option>
 <option value='393'>Islet Cell Transplantation</option>
 <option value='394'>Itching</option>
 <option value='395'>Jaundice</option>
 <option value='396'>Juvenile Rheumatoid Arthritis</option>
 <option value='397'>Kaposi's Sarcoma</option>
 <option value='398'>Kidney Cancer</option>
 <option value='399'>Kidney Diseases</option>
 <option value='400'>Kidney Failure</option>
 <option value='401'>Kidney Stones</option>
 <option value='402'>Kidney Transplantation</option>
 <option value='403'>Klinefelter's Syndrome</option>
 <option value='404'>Knee Injuries and Disorders</option>
 <option value='405'>Knee Replacement</option>
 <option value='406'>Laboratory Tests</option>
 <option value='407'>Lactose Intolerance</option>
 <option value='408'>Laser Eye Surgery</option>
 <option value='409'>Latex Allergy</option>
 <option value='410'>Lead Poisoning</option>
 <option value='411'>Learning Disorders</option>
 <option value='412'>Leg Injuries and Disorders</option>
 <option value='413'>Legionnaires' Disease</option>
 <option value='414'>Leishmaniasis</option>
 <option value='415'>Leukemia, Adult Acute</option>
 <option value='416'>Leukemia, Adult Chronic</option>
 <option value='417'>Leukemia, Childhood</option>
 <option value='418'>Leukodystrophies</option>
 <option value='419'>Lewy Body Disease</option>
 <option value='420'>Listeria Infections</option>
 <option value='421'>Liver Cancer</option>
 <option value='422'>Liver Diseases</option>
 <option value='423'>Liver Transplantation</option>
 <option value='424'>Low Blood Pressure</option>
 <option value='425'>Lung Cancer</option>
 <option value='426'>Lung Diseases</option>
 <option value='427'>Lung Transplantation</option>
 <option value='428'>Lupus</option>
 <option value='429'>Lyme Disease</option>
 <option value='430'>Lymphatic Diseases</option>
 <option value='431'>Lymphoma</option>
 <option value='432'>Macular Degeneration</option>
 <option value='433'>Malaria</option>
 <option value='434'>Male Breast Cancer</option>
 <option value='435'>Mammography</option>
 <option value='436'>Man-Made Disasters</option>
 <option value='437'>Managed Care</option>
 <option value='438'>Marfan Syndrome</option>
 <option value='439'>Marijuana</option>
 <option value='440'>Mastectomy</option>
 <option value='441'>Measles</option>
 <option value='442'>Medicaid</option>
 <option value='443'>Medical Device Safety</option>
 <option value='444'>Medicare</option>
 <option value='445'>Medicare Prescription Drug Coverage</option>
 <option value='446'>Medicines</option>
 <option value='447'>Melanoma</option>
 <option value='448'>Memory</option>
 <option value='449'>Men's Health</option>
 <option value='450'>Meniere's Disease</option>
 <option value='451'>Meningitis</option>
 <option value='452'>Menopause</option>
 <option value='453'>Menstruation</option>
 <option value='454'>Mental Health</option>
 <option value='455'>Mercury</option>
 <option value='456'>Mesothelioma</option>
 <option value='457'>Metabolic Disorders</option>
 <option value='458'>Metabolic Syndrome</option>
 <option value='459'>Methamphetamine</option>
 <option value='460'>Migraine</option>
 <option value='461'>Minerals</option>
 <option value='462'>Mitral Valve Prolapse</option>
 <option value='463'>Mobility Aids</option>
 <option value='464'>Molds</option>
 <option value='465'>Moles</option>
 <option value='466'>Monkeypox Virus Infections</option>
 <option value='467'>Motion Sickness</option>
 <option value='468'>Motor Vehicle Safety</option>
 <option value='469'>Mouth Disorders</option>
 <option value='470'>Movement Disorders</option>
 <option value='471'>MRI Scans</option>
 <option value='472'>MRSA</option>
 <option value='473'>Multiple Myeloma</option>
 <option value='474'>Multiple Sclerosis</option>
 <option value='475'>Mumps</option>
 <option value='476'>Muscle Cramps</option>
 <option value='477'>Muscle Disorders</option>
 <option value='478'>Muscular Dystrophy</option>
 <option value='479'>Myasthenia Gravis</option>
 <option value='480'>Myositis</option>
 <option value='481'>Nail Diseases</option>
 <option value='482'>Nasal Cancer</option>
 <option value='483'>Native-American Health</option>
 <option value='484'>Natural Disasters</option>
 <option value='485'>Nausea and Vomiting</option>
 <option value='486'>Neck Injuries and Disorders</option>
 <option value='487'>Neural Tube Defects</option>
 <option value='488'>Neuroblastoma</option>
 <option value='489'>Neurofibromatosis</option>
 <option value='490'>Neurologic Diseases</option>
 <option value='491'>Neuromuscular Disorders</option>
 <option value='492'>Newborn Screening</option>
 <option value='493'>Noise</option>
 <option value='494'>Nose Disorders</option>
 <option value='495'>Nuclear Scans</option>
 <option value='496'>Nursing Homes</option>
 <option value='497'>Nutrition</option>
 <option value='498'>Nutrition for Seniors</option>
 <option value='499'>Nutritional Support</option>
 <option value='500'>Obesity</option>
 <option value='501'>Obesity in Children</option>
 <option value='502'>Obsessive-Compulsive Disorder</option>
 <option value='503'>Occupational Health</option>
 <option value='504'>Occupational Health for Healthcare Providers</option>
 <option value='505'>Oral Cancer</option>
 <option value='506'>Organ Donation</option>
 <option value='507'>Organ Transplantation</option>
 <option value='508'>Orthodontia</option>
 <option value='509'>Osteoarthritis</option>
 <option value='510'>Osteogenesis Imperfecta</option>
 <option value='511'>Osteonecrosis</option>
 <option value='512'>Osteoporosis</option>
 <option value='513'>Ostomy</option>
 <option value='514'>Ovarian Cancer</option>
 <option value='515'>Ovarian Cysts</option>
 <option value='516'>Over-the-Counter Medicines</option>
 <option value='517'>Ozone</option>
 <option value='518'>Pacemakers and Implantable Defibrillators</option>
 <option value='519'>Paget's Disease of Bone</option>
 <option value='520'>Pain</option>
 <option value='521'>Pain Relievers</option>
 <option value='522'>Pancreas Transplantation</option>
 <option value='523'>Pancreatic Cancer</option>
 <option value='524'>Pancreatic Diseases</option>
 <option value='525'>Panic Disorder</option>
 <option value='526'>Paralysis</option>
 <option value='527'>Parasitic Diseases</option>
 <option value='528'>Parathyroid Disorders</option>
 <option value='529'>Parenting</option>
 <option value='530'>Parkinson's Disease</option>
 <option value='531'>Patient Rights</option>
 <option value='532'>Patient Safety</option>
 <option value='533'>Pelvic Inflammatory Disease</option>
 <option value='534'>Pelvic Pain</option>
 <option value='535'>Pelvic Support Problems</option>
 <option value='536'>Penis Disorders</option>
 <option value='537'>Peptic Ulcer</option>
 <option value='538'>Peripheral Nerve Disorders</option>
 <option value='539'>Peripheral Vascular Diseases</option>
 <option value='540'>Personal Medical Records</option>
 <option value='541'>Personality Disorders</option>
 <option value='542'>Pesticides</option>
 <option value='543'>Pet Health</option>
 <option value='544'>Phenylketonuria</option>
 <option value='545'>Pheochromocytoma</option>
 <option value='546'>Phobias</option>
 <option value='547'>Piercing and Tattoos</option>
 <option value='548'>Pinworms</option>
 <option value='549'>Pituitary Disorders</option>
 <option value='550'>Plague</option>
 <option value='551'>Plastic and Cosmetic Surgery</option>
 <option value='552'>Pneumocystis Infections</option>
 <option value='553'>Pneumonia</option>
 <option value='554'>Poison Ivy, Oak and Sumac</option>
 <option value='555'>Poisoning</option>
 <option value='556'>Polio and Post-Polio Syndrome</option>
 <option value='557'>Polymyalgia Rheumatica</option>
 <option value='558'>Porphyria</option>
 <option value='559'>Post-Traumatic Stress Disorder</option>
 <option value='560'>Postpartum Depression</option>
 <option value='561'>Prader-Willi Syndrome</option>
 <option value='562'>Preconception Care</option>
 <option value='563'>Pregnancy</option>
 <option value='564'>Pregnancy and Substance Abuse</option>
 <option value='565'>Pregnancy Loss</option>
 <option value='566'>Premature Babies</option>
 <option value='567'>Premature Ovarian Failure</option>
 <option value='568'>Premenstrual Syndrome</option>
 <option value='569'>Prenatal Care</option>
 <option value='570'>Prenatal Testing</option>
 <option value='571'>Prescription Drug Abuse</option>
 <option value='572'>Pressure Sores</option>
 <option value='573'>Progressive Supranuclear Palsy</option>
 <option value='574'>Prostate Cancer</option>
 <option value='575'>Prostate Diseases</option>
 <option value='576'>Psoriasis</option>
 <option value='577'>Psychotic Disorders</option>
 <option value='578'>Pulmonary Embolism</option>
 <option value='579'>Pulmonary Fibrosis</option>
 <option value='580'>Pulmonary Hypertension</option>
 <option value='581'>Rabies</option>
 <option value='582'>Radiation Exposure</option>
 <option value='583'>Radiation Therapy</option>
 <option value='584'>Radon</option>
 <option value='585'>Rape</option>
 <option value='586'>Rare Diseases</option>
 <option value='587'>Rashes</option>
 <option value='588'>Raynaud's Disease</option>
 <option value='589'>Refractive Errors</option>
 <option value='590'>Rehabilitation</option>
 <option value='591'>Reproductive Health</option>
 <option value='592'>Respiratory Syncytial Virus Infections</option>
 <option value='593'>Restless Legs</option>
 <option value='594'>Retinal Disorders</option>
 <option value='595'>Rett Syndrome</option>
 <option value='596'>Reye Syndrome</option>
 <option value='597'>Rheumatoid Arthritis</option>
 <option value='598'>Rickets</option>
 <option value='599'>Rosacea</option>
 <option value='600'>Rotavirus Infections</option>
 <option value='601'>Rubella</option>
 <option value='602'>Rural Health Concerns</option>
 <option value='603'>Safety</option>
 <option value='604'>Salivary Gland Disorders</option>
 <option value='605'>Salmonella Infections</option>
 <option value='606'>Sarcoidosis</option>
 <option value='607'>Scabies</option>
 <option value='608'>Scars</option>
 <option value='609'>Schizophrenia</option>
 <option value='610'>School Health</option>
 <option value='611'>Sciatica</option>
 <option value='612'>Scleroderma</option>
 <option value='613'>Scoliosis</option>
 <option value='614'>Seasonal Affective Disorder</option>
 <option value='615'>Secondhand Smoke</option>
 <option value='616'>Seizures</option>
 <option value='617'>Seniors' Health</option>
 <option value='618'>Sepsis</option>
 <option value='619'>Severe Acute Respiratory Syndrome</option>
 <option value='620'>Sexual Health</option>
 <option value='621'>Sexually Transmitted Diseases</option>
 <option value='622'>Shingles</option>
 <option value='623'>Shoulder Injuries and Disorders</option>
 <option value='624'>Sickle Cell Anemia</option>
 <option value='625'>Sinusitis</option>
 <option value='626'>Sjogren's Syndrome</option>
 <option value='627'>Skin Aging</option>
 <option value='628'>Skin Cancer</option>
 <option value='629'>Skin Conditions</option>
 <option value='630'>Skin Pigmentation Disorders</option>
 <option value='631'>Sleep Apnea</option>
 <option value='632'>Sleep Disorders</option>
 <option value='633'>Smallpox</option>
 <option value='634'>Smokeless Tobacco</option>
 <option value='635'>Smoking</option>
 <option value='636'>Smoking and Youth</option>
 <option value='637'>Smoking Cessation</option>
 <option value='638'>Snoring</option>
 <option value='639'>Soft Tissue Sarcoma</option>
 <option value='640'>Speech and Communication Disorders</option>
 <option value='641'>Spina Bifida</option>
 <option value='642'>Spinal Cord Diseases</option>
 <option value='643'>Spinal Cord Injuries</option>
 <option value='644'>Spinal Diseases</option>
 <option value='645'>Spinal Muscular Atrophy</option>
 <option value='646'>Spinal Stenosis</option>
 <option value='647'>Spleen Diseases</option>
 <option value='648'>Sports Fitness</option>
 <option value='649'>Sports Injuries</option>
 <option value='650'>Sports Safety</option>
 <option value='651'>Sprains and Strains</option>
 <option value='652'>Staphylococcal Infections</option>
 <option value='653'>Stem Cells</option>
 <option value='654'>Stomach Cancer</option>
 <option value='655'>Stomach Disorders</option>
 <option value='656'>Streptococcal Infections</option>
 <option value='657'>Stress</option>
 <option value='658'>Stroke</option>
 <option value='659'>Stuttering</option>
 <option value='660'>Sudden Infant Death Syndrome</option>
 <option value='661'>Suicide</option>
 <option value='662'>Sun Exposure</option>
 <option value='663'>Surgery</option>
 <option value='664'>Swallowing Disorders</option>
 <option value='665'>Sweat</option>
 <option value='666'>Syphilis</option>
 <option value='667'>Syringomyelia</option>
 <option value='668'>Tailbone Disorders</option>
 <option value='669'>Talking With Your Doctor</option>
 <option value='670'>Taste and Smell Disorders</option>
 <option value='671'>Tay-Sachs Disease</option>
 <option value='672'>Teen Development</option>
 <option value='673'>Teen Health</option>
 <option value='674'>Teen Mental Health</option>
 <option value='675'>Teen Sexual Health</option>
 <option value='676'>Teen Violence</option>
 <option value='677'>Teenage Pregnancy</option>
 <option value='678'>Teens' Page</option>
 <option value='679'>Temporomandibular Joint Dysfunction</option>
 <option value='680'>Tendinitis</option>
 <option value='681'>Testicular Cancer</option>
 <option value='682'>Testicular Disorders</option>
 <option value='683'>Tetanus</option>
 <option value='684'>Thalassemia</option>
 <option value='685'>Thoracic Outlet Syndrome</option>
 <option value='686'>Throat Disorders</option>
 <option value='687'>Thrombophlebitis</option>
 <option value='688'>Thymus Cancer</option>
 <option value='689'>Thyroid Cancer</option>
 <option value='690'>Thyroid Diseases</option>
 <option value='691'>Tick Bites</option>
 <option value='692'>Tinea Infections</option>
 <option value='693'>Tinnitus</option>
 <option value='694'>Toe Injuries and Disorders</option>
 <option value='695'>Toilet Training</option>
 <option value='696'>Tonsils and Adenoids</option>
 <option value='697'>Tooth Disorders</option>
 <option value='698'>Tourette Syndrome</option>
 <option value='699'>Toxoplasmosis</option>
 <option value='700'>Transient Ischemic Attack</option>
 <option value='701'>Traveler's Health</option>
 <option value='702'>Tremor</option>
 <option value='703'>Trichomoniasis</option>
 <option value='704'>Trigeminal Neuralgia</option>
 <option value='705'>Triglycerides</option>
 <option value='706'>Tuberculosis</option>
 <option value='707'>Tuberous Sclerosis</option>
 <option value='708'>Turner Syndrome</option>
 <option value='709'>Twins, Triplets, Multiple Births</option>
 <option value='710'>Ulcerative Colitis</option>
 <option value='711'>Ultrasound</option>
 <option value='712'>Understanding Medical Research</option>
 <option value='713'>Urinary Incontinence</option>
 <option value='714'>Urinary Tract Infections</option>
 <option value='715'>Usher Syndrome</option>
 <option value='716'>Uterine Cancer</option>
 <option value='717'>Uterine Diseases</option>
 <option value='718'>Uterine Fibroids</option>
 <option value='719'>Vaginal Cancer</option>
 <option value='720'>Vaginal Diseases</option>
 <option value='721'>Varicose Veins</option>
 <option value='722'>Vascular Diseases</option>
 <option value='723'>Vasculitis</option>
 <option value='724'>Vegetarian Diet</option>
 <option value='725'>Veterans and Military Health</option>
 <option value='726'>Viral Infections</option>
 <option value='727'>Vision Impairment and Blindness</option>
 <option value='728'>Vitamins</option>
 <option value='729'>Vitiligo</option>
 <option value='730'>Voice Disorders</option>
 <option value='731'>Von Hippel-Lindau Disease</option>
 <option value='732'>Vulvar Cancer</option>
 <option value='733'>Vulvar Disorders</option>
 <option value='734'>Warts</option>
 <option value='735'>Water Pollution</option>
 <option value='736'>Water Safety (Recreational)</option>
 <option value='737'>Wegener's Granulomatosis</option>
 <option value='738'>Weight Control</option>
 <option value='739'>Weight Loss Surgery</option>
 <option value='740'>West Nile Virus</option>
 <option value='741'>Whooping Cough</option>
 <option value='742'>Wilms' Tumor</option>
 <option value='743'>Wilson Disease</option>
 <option value='744'>Women's Health</option>
 <option value='745'>Wounds</option>
 <option value='746'>Wrist Injuries and Disorders</option>
 <option value='747'>X-Rays</option>
 <option value='748'>Yeast Infections</option>
 </select>
 	<input type=hidden value='select' name='select'>
	<input type=submit value='Go' name='submit'>
		</form></small></p>
XXX;
	return $alpha.$out.$x."<p>Search <a target='_new' href=http://medlineplus.gov/>MedlinePlus&#174;</a> to find authoritative consumer health information</p>";

}
?>