<?php
require_once "alib.inc.php";
require_once "layout.inc.php";
require_once "gx.inc.php";
// Group Creator and Editor


list($accid,$fn,$ln,$email,$idp,$cookie) = aconfirm_logged_in (); // does not return if not lo
$db = aconnect_db(); // connect to the right database

if (!isset($_REQUEST['submit']))
{

	$bodycode = <<<XXX
&lt;div&gt;
&lt;ul&gt;
&lt;li&gt;&lt;a href='link1'&gt;<i>group wiki, blog, or phr</i>&lt;/a&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;/div&gt;
XXX;

	$headercode = <<<XXX
&lt;style&gt;&nbsp;&lt;/style&gt;
&lt;script&gt;&nbsp;&lt;/script&gt;
XXX;

	if (isset($_REQUEST['t'])){
		$t = $_REQUEST['t'];
		// pull the template in and parse it

		$s = file_get_contents("/var/www/php/groups/$accid-$t-gx.htm");

		$p1 = strpos($s,$__top);
		if ($p1===false) parse_error();

		$p2 = strpos ($s,$__middle);
		if ($p2===false) parse_error();

		$p3 = strpos ($s,$__bottom);
		if ($p3===false) parse_error();

		$headercode = substr($s,$p1+$__toplen+1,$p2-$__toplen-$p1-3);

		$bodycode = substr($s, $p2+$__middlelen+2,$p3-$p2-$__middlelen-3);

	}
	else $t='unassigned';

	$html =<<<XXX
<form action=GxEditor.php method=post>
<h2>Create and Customize Your Group</h2><small>if the group doesnt exist it will be created and you will be its administrator<br>
we are currently <i>totally replacing</i> the group every time it is changed</small>
<p>Your Group Name (1-32 characters): <input type=text size=32 name=name value='$t'/>
<p>You can customize your group page to provide links to useful wikis, forums, blogs, sites,
and any other places of interest. <br>
You can also put interesting, anonymous, PHRs on this page.
<p>Please choose your audience type
<select name=type>
  <option value ="5">Only members of this group (login will be required)</option>
  <option value ="4">Anyone with a valid MedCommons ID (login will be required)</option>
  <option value ="1">Everyone on the Internet (no login required)</option>
</select>

<p>
<h3>HEAD Section</h3>
You can put css and javascript functions in here, they will be merged into your page<br>
<textarea rows="5" cols="80" name=codehead>
$headercode
</textarea><br>
<p>
<h3>BODY Section</h3>
You can put your actual content in here, they will be merged into your page<br>
The sample html below generates a bulleted list of hyperlinks<br>
<textarea rows="10" cols="80" name=codebody>
$bodycode
</textarea><br>
<input type=submit name=submit value=upload>
</form>
XXX;

	echo std("Group Page Editor",
	"MedCommons Group Page Editor",
	false,
	false,
	stdlayout ( $html));
}
else
{
	// this is the postback handler, right here

	$type=$_REQUEST['type'];
	$name=$_REQUEST['name'];

	$codehead=$_REQUEST['codehead'];
	$codebody=$_REQUEST['codebody'];

	$time =  gmstrftime("%b %d %Y %H:%M:%S");
	;

	$pre = "
// module autogenerated by GxEditor on $time 
// uploader: $accid $email
--------BEGIN HEADER CODE--------------
";
	$middle = "----------END HEADER BEGIN BODY CODE-----------\r\n";
	$post = "
----------END BODY CODE-----------------------";

	file_put_contents('/var/www/php/groups/'.$accid.'-'.$name.'-gx.htm',
	$pre.$codehead.$middle.$codebody.$post);

	// put a group into the groupinstances table, first find the highest id and bump it
	// we need this before we insert the recofrd
	$select = "select groupinstanceid from groupinstances order by groupinstanceid desc limit 1";
	$result = mysql_query($select) or die("Can not select $select");
	$m = mysql_Fetch_array($result);
	$maxid = $m[0]+1; // really should add a transaction around all this
	$memberUrl = "Gx.php?t=$name";
	$adminUrl = "GxEditor.php?t=$name";
	$insert = "REPLACE into groupinstances SET groupinstanceid='$maxid',grouptypeid='$type',name='$name',
    memberUrl='$memberUrl',
    adminUrl='$adminUrl'
    ";
	mysql_query($insert)or die("Can not insert $insert");
	$rowcount = mysql_affected_rows();
	$dupe = ($rowcount !=1 );
	if ($dupe) $out=  "<h3>Group $name already exists, it has been updated</h3>"; else 
	$out=  "<h3>Group $name has been created</h3>";
	//make this user administrator of this group
	$insert = "REPLACE into groupadmins SET groupinstanceid='$maxid',adminaccid='$accid',comment='added by GxStoreCode at $time'";
	mysql_query($insert);
	$rowcount = mysql_affected_rows();
	$dupe = ($rowcount !=1 );
	if ($dupe) $out.= "You were already an administrator of group: $name <br>"; else
	$out.= "You are now administrator of group: $name <br>";
	$name = urlencode($name);
	$out.= "Your group landing page was stored and can be viewed <a target='_new' href='Gx.php?t=$name' >here</a><br>";
	$out.= "<small>We will be changing the url to https://groups.medcommons.net/".$name."</small><br>";
	
	echo std("Group $name Page Editor",
	"MedCommons Group Page Editor",
	false,
	false,
	stdlayout ( $out));
}
?>