#!/bin/sh

# mc_locals        Start/Stop the mc_locals daemon.
#
# chkconfig: 2345 90 60
# description: mc_locals is a SOAP/REST server that allocates
#              16-digit MedCommons IDs and 12-digit tracking numbers.
#              These MCIDs are unique in the universe.
#
# processname: mc_locals
# pidfile: /var/run/mc_locals.pid
#
# Source function library.
. /etc/init.d/functions

prog="mc_locals"

start() {
	echo -n $"Starting $prog: "
	if [ -e /var/run/${prog}.pid ] && [ -e /proc/`cat /var/run/${prog}.pid` ]; then
		echo -n $"Cannot start ${prog}: ${prog} is already running."
		failure $"cannot start ${prog}: ${prog} already running."
		echo
		return 1
	fi
	daemon /usr/sbin/${prog}.py -C /usr/etc/${prog}.rc
	RETVAL=$?
	echo
	return $RETVAL
}

stop() {
	echo -n $"Stopping $prog: "
	if [ ! -e /var/run/${prog}.pid ] || [ ! -e /proc/`cat /var/run/${prog}.pid` ]; then
		echo -n $"cannot stop ${prog}: ${prog} is not running.";
		failure $"cannot stop ${prog}: ${prog} is not running."
		echo
		return 1;
	fi
	killproc ${prog}
	RETVAL=$?
	echo
	return $RETVAL
}

rhstatus() {
	status ${prog}
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  reload)
	restart
	;;
  status)
	rhstatus
	;;
  *)
	echo $"Usage: $0 {start|stop|status|reload|restart}"
	exit 
esac
