<?php
require_once "is.inc.php";

function linewrap ($s)
{
	return "
	$s";
}
function process_simtrak_dd_table($table,$rr)
{
	global $bufa;
	$bufa='';
	switch ($rr['fieldtype']	)
	{
		case 'C':
		case 'D':
		case 'M':
		case 'L':
		case 'G':
		case 'N':
		default: 
		$bufa .= linewrap("  `{$rr['fieldname']}` varchar({$rr['length']}) NOT NULL, -- {$rr['description']}   " );
		//die ("unknown fieldtype");

	}
	return $bufa;
}
//main starts here
header("Content-type: text/plain");

$ops = array ('create_schema');//,'create_schema');

$gmt = strftime('%T %D');

$tables=array();//a full platter of tables
$result = dosql("Select distinct ddtable from datadictionary");
while ($r=isdb_fetch_object($result)) $tables[] = $r->ddtable;
mysql_free_result($result);
//do the same thing for each distinct table

	foreach ($ops as $op)
	{
		foreach ($tables as $table)
		{
		$mid='';
		switch ($op)
		{
			case 'create_schema':

				$top = <<<XXX

--
--  Table structure for table $table
--  Generated by MedCommons stbuilder @ $gmt

CREATE TABLE IF NOT EXISTS $table (  `id` int(11) NOT NULL auto_increment,
XXX;
				$result = xsql("Select * from datadictionary where ddtable='$table' ");
				while ($r=isdb_fetch_array($result)) $mid .= process_simtrak_dd_table($table,$r);
				mysql_free_result($result);
				$bottom = <<<XXX
  PRIMARY KEY  (`id`)) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;	
XXX;


				break;

			default: die ("Invalid op $op");
		}

		echo linewrap($top).$mid.linewrap($bottom);
	}
}

//that's about all

?>