yum remove Django.noarch
yum remove MySQL-python.i386
yum remove PyXML.i386
yum remove SOAPpy.noarch
yum remove audit-libs-python.i386
yum remove checkpolicy.i386
yum remove distcache.i386
yum remove gmp.i386
yum remove jdk.i586
yum remove libmcrypt.i386
yum remove libselinux-python.i386
yum remove libsemanage.i386
yum remove libxslt.i386
yum remove medcommons-DDL.noarch
yum remove medcommons-config.noarch
yum remove medcommons-console.noarch
yum remove medcommons-developers.noarch
yum remove medcommons-gateway.noarch
yum remove medcommons-identity.noarch
yum remove medcommons-jai.i586
yum remove medcommons-jsvc.i386
yum remove medcommons-mc_backups.noarch
yum remove medcommons-mc_locals.noarch
yum remove medcommons-php.noarch
yum remove medcommons-schema.noarch
yum remove medcommons-tomcat-native.i386
yum remove medcommons-tomcat.noarch
yum remove medcommons.noarch
yum remove mod_python.i386
yum remove mod_ssl.i386
yum remove mx.i386
yum remove mysql-libs.i386
yum remove mysql-server.i386
yum remove mysql.i386
yum remove perl-DBD-MySQL.i386
yum remove perl-DBI.i386
yum remove php-cli.i386
yum remove php-common.i386
yum remove php-gd.i386
yum remove php-mbstring.i386
yum remove php-mcrypt.i386
yum remove php-mysql.i386
yum remove php-pdo.i386
yum remove php-pear-DB.noarch
yum remove php-pear.noarch
yum remove php-soap.i386
yum remove php-xml.i386
yum remove php.i386
yum remove phpMyAdmin.noarch
yum remove policycoreutils.i386
yum remove python-crypto.i386
yum remove python-fpconst.noarch
yum remove python-imaging.i386
yum remove selinux-policy.noarch
yum remove sendmail-cf.i386

yum install apr-devel.i386
yum install apr-util-devel.i386
yum install cyrus-sasl-devel.i386
yum install db4-devel.i386
yum install expat-devel.i386
yum install mod_dav_svn.i386
yum install neon.i386
yum install openldap-devel.i386
yum install perl-URI.noarch
yum install subversion-devel.i386
yum install subversion.i386
